# Generated by Django 4.0.2 on 2022-02-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
